# This is a basic workflow to help you get started with Actions

name: publish app on google cloud run

env:
  service-name: "cors-proxy-api"
  image-name: "cors-proxy-api"
  container-port: 3000
  max-num-instances: 5
  concurrency: 80
  cpu: 1
  memory: 2Gi


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called " publish-api"
  publish-api:
    # The type of runner that the job will run on
    runs-on:  "ubuntu-latest"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build docker image
        run:  docker build -t eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.image-name }}:latest . 

      - name: Push to Google Container Registry
        run:  docker push eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.image-name }}:latest   

      - name: Deploy to Cloud Run
        run: |
         gcloud run deploy ${{ env.service-name }} --image eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.image-name }}:latest \
         --region europe-west3 --concurrency ${{ env.concurrency  }} --cpu ${{ env.cpu }}  --max-instances ${{ env.max-num-instances }} \
         --memory ${{ env.memory }} --port ${{ env.container-port }} --set-env-vars=JWT_SECRET=${{ secrets.JWT_SECRET }},PROXY_URL=${{ secrets.PROXY_URL }}  --allow-unauthenticated